#!/bin/sh
####        Created by Jarin Martin 2020               #####
####    Inspiration from various other Jamf admins    ######
#####      tackling similar issues.           ##############



###########################
#### RENAME COMPUTER ######
##########################

### Who is logged in, dawg? We need answers, we need them now. ###
getUser=$(ls -l /dev/console | awk '{ print $3 }')

### You know who, now what, nerd? "Oh, build the name, aight dawg,I got this" ###
firstInitial=$(finger -s $getUser | head -2 | tail -n 1 | awk '{print toupper($2)}' | cut -c 1)
lastName=$(finger -s $getUser | head -2 | tail -n 1 | awk '{print toupper($3)}')
type=$(sysctl -n hw.model | cut -d "," -f 1 | tr -d '[0-9]_')


### I did the math, I said, "how about first inital, last name and then device type?" Okay, Full send. ###
computerName=$firstInitial$lastName"_"$type


### SET THE NAME IN ALL THE PLACES!!! ###
###################################
#─────────────────────────────▄██▄
#─────────────────────────────▀███
#────────────────────────────────█
#───────────────▄▄▄▄▄────────────█
#──────────────▀▄────▀▄──────────█
#──────────▄▀▀▀▄─█▄▄▄▄█▄▄─▄▀▀▀▄──█
#─────────█──▄──█────────█───▄─█─█
#─────────▀▄───▄▀────────▀▄───▄▀─█
#──────────█▀▀▀────────────▀▀▀─█─█
#──────────█───────────────────█─█
#▄▀▄▄▀▄────█──▄█▀█▀█▀█▀█▀█▄────█─█
#█▒▒▒▒█────█──█████████████▄───█─█
#█▒▒▒▒█────█──██████████████▄──█─█
#█▒▒▒▒█────█───██████████████▄─█─█
#█▒▒▒▒█────█────██████████████─█─█
#█▒▒▒▒█────█───██████████████▀─█─█
#█▒▒▒▒█───██───██████████████──█─█
#▀████▀──██▀█──█████████████▀──█▄█
#──██───██──▀█──█▄█▄█▄█▄█▄█▀──▄█▀
#──██──██────▀█─────────────▄▀▓█
#──██─██──────▀█▀▄▄▄▄▄▄▄▄▄▀▀▓▓▓█
#──████────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
#──███─────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
#──██──────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
#──██──────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
#──██─────────▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
#──██────────▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
#──██───────▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▌
#──██──────▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▌
#──██─────▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▌
#──██────▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▌
#################################


/usr/sbin/scutil --set ComputerName "$computerName"
/usr/sbin/scutil --set LocalHostName "$computerName"
/usr/sbin/scutil --set HostName "$computerName"


### I Guess we should probably tell jamf... ###

/usr/local/bin/jamf recon


exit 0
